apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with (include "common.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
      annotations:
        {{- if .Values.config.enabled }}
        checksum/config: {{ .Values.config.data | toYaml | sha256sum }}
        {{- end }}
        {{- with (include "common.annotations" .) }}
        {{- . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "common.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- include "common.imagePullSecrets" . | nindent 6 }}
      {{- include "common.podSecurityContext" . | nindent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- include "common.container.image" . | nindent 10 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- include "common.env" . | nindent 10 }}
          {{- if .Values.config.enabled }}
          envFrom:
            - configMapRef:
                name: {{ include "common.fullname" . }}
          {{- end }}
          {{- include "common.resources" . | nindent 10 }}
          {{- include "common.probes" . | nindent 10 }}
          {{- include "common.securityContext" . | nindent 10 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "common.scheduling" . | nindent 6 }}
